apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager

resources:
  - configmap.yaml
  - secret.yaml
  - minio-secret.yaml
  - s3-csi.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - minio.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml
  - ingress.yaml

